[package]
name = "polynomial"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.4"
ark-std = "0.5.0"
ark-ff = "0.5.0"
rand = "0.8.5"
ark-bn254 = "0.5.0"
sha2 = "0.10.8"
ark-crypto-primitives = {version = "0.5.0", features = ["sponge"]}
sha3 = "0.10.8"
